name: Run Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Print message
        run: echo "This workflow ran at $(date) every 10 minutes!"
